spring.application.name=LogiCore
server.port=9909

# إعدادات PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/logicoredb
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# أوامر Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
